apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-test-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LaurentiuDaniel94/k3s-raspi-gitOps.git
    targetRevision: HEAD
    path: argo-test/argo-apps
    helm:
      version: v3
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true