apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/LaurentiuDaniel94/k3s-raspi-gitOps.git'
    targetRevision: HEAD
    path: argo-test/charts/kube-prometheus-stack
    helm:
      valueFiles:
        - ../../environments/prod/kube-prometheus-stack-values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
