apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: default
  source:
    path: charts/kyverno-policy-reporter/policy-reporter
    repoURL: 'https://github.com/LaurentiuDaniel94/k3s-raspi-gitOps.git'
    targetRevision: HEAD 
    helm:
      version: v3
      valueFiles:
        - ../../environments/dev/kyverno-policy-reporter-values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true