# environments/dev/longhorn-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashicorp-vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LaurentiuDaniel94/k3s-raspi-gitOps.git
    path: charts/vault/vault
    targetRevision: HEAD
    helm:
      valueFiles:
        - argo-test/environments/dev/hashicorp-vault-app.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
