# environments/dev/longhorn-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LaurentiuDaniel94/k3s-raspi-gitOps.git
    path: charts/prometheus-stack/kube-prometheus-stack
    targetRevision: HEAD
    helm:
      valueFiles:
        - environments/dev/prometheus-stack-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
